# DataSource settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blume
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true