# DataSource settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blume
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

application:
  security:
    jwt:
      secret-key: 927814c154bb1be99ddbc9382f72c96e8f0a2c95cb0b7d2c0f1e2263f8c13e2f
      expiration: 86400000 # a day
      refresh-token:
          expiration: 604800000 # 7 days